### PR TITLE
deep equal

### PR DESCRIPTION
**Pull request by besarthoxhaj**
@gabrielperales could you check it please :)

### CODE REVIEW

**Comment by gabrielperales** [comment]
Let me check it tomorrow ;)

**Comment by besarthoxhaj** [comment]
People did such a good job this morning! Updated with their solution!:)

**Comment by gabrielperales** [comment]
Very nice!, I think the only edges cases left are `null`, `undefined` and maybe `NaN`.

**Comment by besarthoxhaj** [comment]
Yeah and also `deepEqual([],{});` and others :D

**Pull request merged**
